baseurl: "/Toezicht-en-Handhavenservices"
apiname: "Toezicht- en Handhavenservices"
versie-nr: "2.0"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: StUF-BG
    subnav:
      - title: Overzicht
        path: /
      - title: Documentatie  
        path: /Documentatie
#      - title: Werkgroep  
#        path: /Werkgroep 

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: melsk-r/jekyll-theme-vng-realisatie

github: VNG-Realisatie/Toezicht-en-Handhavenservices

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/Toezicht-en-Handhavenservices

standard_family: StUF
